# config\spider_config.yml
scan_paths:
  - "/etc"
  - "/opt"
  - "/var/log"

scan_settings:
  max_files_per_path: 1000
  max_file_size: 50000
  chunk_size: 10000

llm_settings:
  model_type: "placeholder"
  max_context: 50000

schedule:
  full_scan_interval: "6h"
  quick_scan_interval: "30m"

exclusions:
  - "proc"
  - "sys" 
  - "dev"
  - "run"
  - "tmp"
  - "__pycache__"
  - ".git"

# remote server configurations
remote_servers:
  sanctum:
    host: "192.168.1.254"
    user: "abidan"
    ssh_key: "/home/spider/.ssh/spider_remote"

# casaos awareness settings
casaos:
  ubuntu_server_detection: true
  casaos_containers_expected: true
  normal_disk_usage_expectations: true
